development:
  adapter: mysql2
  host: <%= ENV.fetch('DB_HOST') %>
  database: <%= ENV.fetch('DB_NAME') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  timeout: 5000