version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    restart: always

  app:
    build: .
    ports:
      - "3030:3030"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
