source 'https://rubygems.org'

ruby '~> 3.0.0'

gem 'sinatra'
gem 'json'

# incluimos mongo db

# gem 'mongo'
# gem 'mongoid'

gem 'puma'
gem 'rackup'

gem 'activerecord', '~> 6.1'
gem 'mysql2', '~> 0.5' 
gem 'sinatra-activerecord'
gem 'rake'